local M = {}

--- @param c Colorscheme The color palette
--- @param config Config
M.setup = function(c, config, _)
  local styles = config.styles
  return {
    -- type
    ["@lsp.type.class"] = { link = "Structure" },
    ["@lsp.type.decorator"] = { link = "Function" },
    ["@lsp.type.enum"] = { link = "Structure" },
    ["@lsp.type.enumNumber"] = { link = "Constant" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.interface"] = { link = "Structure" },
    ["@lsp.type.macro"] = { link = "Macro" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.namespace"] = { link = "Include" },
    ["@lsp.type.parameter"] = { fg = c.base.orange, italic = styles.parameter.italic },
    ["@lsp.type.property"] = { link = "Identifier" },
    ["@lsp.type.struct"] = { link = "Structure" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.typeParameter"] = { link = "Type" },
    ["@lsp.type.variable"] = { link = "Identifier" },

    -- mod
    -- ["@lsp.mod.declaration"] = { fg = c.base.cyan },
    -- ["@lsp.mod.definition"] = { fg = c.base.cyan },
    -- ["@lsp.mod.readonly"] = { fg = c.base.magenta },
    -- ["@lsp.mod.static"] = {},
    ["@lsp.mod.deprecated"] = { strikethrough = true },
    -- ["@lsp.mod.abstract"] = {},
    -- ["@lsp.mod.async"] = {},
    -- ["@lsp.mod.modification"] = {},
    -- ["@lsp.mod.documentation"] = {},
    -- ["@lsp.mod.defaultLibrary"] = {},

    ["@lsp.typemod.class.defaultLibrary"] = { link = "Type" },
    -- ["@lsp.typemod.decorator"] = {},
    -- ["@lsp.typemod.enum"] = {},
    -- ["@lsp.typemod.enumNumber"] = {},
    ["@lsp.typemod.function.declaration"] = { link = "Function" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "Function" },
    -- ["@lsp.typemod.interface"] = {},
    -- ["@lsp.typemod.macro"] = {},
    -- ["@lsp.typemod.method"] = {},
    -- ["@lsp.typemod.namespace"] = {},
    ["@lsp.typemod.parameter.declaration"] = { fg = c.base.orange, italic = styles.parameter.italic },
    -- ["@lsp.typemod.property"] = {},
    -- ["@lsp.typemod.struct"] = {},
    -- ["@lsp.typemod.type"] = {},
    -- ["@lsp.typemod.typeParameter"] = {},
    ["@lsp.typemod.variable.readonly"] = { link = "Identifier" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "Identifier" },
    ["@lsp.typemod.variable.global.lua"] = { link = "Identifier" },
    ["@lsp.typemod.keyword.documentation"] = { link = "Type" },
    -- Dockerfile
    ["@lsp.type.parameter.dockerfile"] = {}, -- using treesitter instead

    -- Cpp
    ["@lsp.type.namespace.cpp"] = { link = "Include" },

    -- Go
    ["@lsp.type.namespace.go"] = { link = "Include" },
    ["@lsp.type.function.go"] = { link = "Function" },
    ["@lsp.type.method.go"] = { link = "Function" },
    ["@lsp.type.type.go"] = { link = "Type" },
    ["@lsp.type.struct.go"] = { fg = c.base.cyan, italic = styles.structure.italic },
    ["@lsp.type.interface.go"] = { fg = c.base.cyan, italic = styles.structure.italic },
    ["@lsp.type.parameter.go"] = { fg = c.base.orange, italic = styles.parameter.italic },
    ["@lsp.type.variable.go"] = { link = "Identifier" },
    ["@lsp.type.typeParameter.go"] = { link = "Type" },
    ["@lsp.typemod.function.definition.go"] = { link = "Function" },
    ["@lsp.typemod.method.definition.go"] = { link = "Function" },
    ["@lsp.typemod.variable.readonly.go"] = { link = "Identifier" },
    ["@lsp.typemod.type.defaultLibrary.go"] = { fg = c.base.cyan, italic = true },
    ["@lsp.typemod.function.defaultLibrary.go"] = { link = "Function" },
    ["@lsp.typemod.variable.defaultLibrary.go"] = { link = "Identifier" },

    -- TypeScript / JavaScript
    ["@lsp.type.class.typescript"] = { link = "Type" },
    ["@lsp.type.class.javascript"] = { link = "Type" },
    ["@lsp.type.enum.typescript"] = { link = "Type" },
    ["@lsp.type.enumMember.typescript"] = { link = "Constant" },
    ["@lsp.type.enumMember.javascript"] = { link = "Constant" },
    ["@lsp.type.interface.typescript"] = { fg = c.base.cyan, italic = styles.structure.italic },
    ["@lsp.type.namespace.typescript"] = { link = "Include" },
    ["@lsp.type.namespace.javascript"] = { link = "Include" },
    ["@lsp.type.parameter.typescript"] = { fg = c.base.orange, italic = styles.parameter.italic },
    ["@lsp.type.parameter.javascript"] = { fg = c.base.orange, italic = styles.parameter.italic },
    ["@lsp.type.property.typescript"] = { link = "Identifier" },
    ["@lsp.type.property.javascript"] = { link = "Identifier" },
    ["@lsp.type.type.typescript"] = { link = "Type" },
    ["@lsp.type.typeParameter.typescript"] = { fg = c.base.orange },
    ["@lsp.typemod.class.defaultLibrary.typescript"] = { link = "Type" },
    ["@lsp.typemod.class.defaultLibrary.javascript"] = { link = "Type" },
    ["@lsp.typemod.function.defaultLibrary.typescript"] = { link = "Function" },
    ["@lsp.typemod.function.defaultLibrary.javascript"] = { link = "Function" },
    ["@lsp.typemod.variable.defaultLibrary.typescript"] = { link = "Identifier" },
    ["@lsp.typemod.variable.defaultLibrary.javascript"] = { link = "Identifier" },
    ["@lsp.typemod.variable.readonly.typescript"] = { link = "Identifier" },
    ["@lsp.typemod.variable.readonly.javascript"] = { link = "Identifier" },
    ["@lsp.typemod.member.declaration.typescript"] = { link = "Identifier" },
    ["@lsp.typemod.member.declaration.javascript"] = { link = "Identifier" },
    ["@lsp.typemod.function.async.typescript"] = { link = "Function" },
    ["@lsp.typemod.function.async.javascript"] = { link = "Function" },
    ["@lsp.typemod.method.async.typescript"] = { link = "Function" },
    ["@lsp.typemod.method.async.javascript"] = { link = "Function" },

    -- TSX / JSX (React)
    ["@lsp.type.class.typescriptreact"] = { link = "Type" },
    ["@lsp.type.class.javascriptreact"] = { link = "Type" },
    ["@lsp.type.interface.typescriptreact"] = { fg = c.base.cyan, italic = styles.structure.italic },
    ["@lsp.type.enum.typescriptreact"] = { link = "Type" },
    ["@lsp.type.enumMember.typescriptreact"] = { link = "Constant" },
    ["@lsp.type.enumMember.javascriptreact"] = { link = "Constant" },
    ["@lsp.type.namespace.typescriptreact"] = { link = "Include" },
    ["@lsp.type.namespace.javascriptreact"] = { link = "Include" },
    ["@lsp.type.parameter.typescriptreact"] = { fg = c.base.orange, italic = styles.parameter.italic },
    ["@lsp.type.parameter.javascriptreact"] = { fg = c.base.orange, italic = styles.parameter.italic },
    ["@lsp.type.property.typescriptreact"] = { link = "Identifier" },
    ["@lsp.type.property.javascriptreact"] = { link = "Identifier" },
    ["@lsp.type.type.typescriptreact"] = { link = "Type" },
    ["@lsp.type.typeParameter.typescriptreact"] = { fg = c.base.orange },
    ["@lsp.typemod.class.defaultLibrary.typescriptreact"] = { link = "Type" },
    ["@lsp.typemod.class.defaultLibrary.javascriptreact"] = { link = "Type" },
    ["@lsp.typemod.function.defaultLibrary.typescriptreact"] = { link = "Function" },
    ["@lsp.typemod.function.defaultLibrary.javascriptreact"] = { link = "Function" },
    ["@lsp.typemod.variable.defaultLibrary.typescriptreact"] = { link = "Identifier" },
    ["@lsp.typemod.variable.defaultLibrary.javascriptreact"] = { link = "Identifier" },
    ["@lsp.typemod.variable.readonly.typescriptreact"] = { link = "Identifier" },
    ["@lsp.typemod.variable.readonly.javascriptreact"] = { link = "Identifier" },
    ["@lsp.typemod.function.async.typescriptreact"] = { link = "Function" },
    ["@lsp.typemod.function.async.javascriptreact"] = { link = "Function" },
    ["@lsp.typemod.method.async.typescriptreact"] = { link = "Function" },
    ["@lsp.typemod.method.async.javascriptreact"] = { link = "Function" },

    -- Python
    ["@lsp.type.decorator.python"] = { fg = c.base.dimmed2 },
    ["@lsp.type.parameter.python"] = {},
    ["@lsp.type.function.python"] = { link = "Function" },
    ["@lsp.type.class.python"] = {},
    ["@lsp.mod.definition.python"] = {},
    ["@lsp.typemod.function.definition.python"] = { link = "Function" },
    ["@lsp.typemod.parameter.definition.python"] = { fg = c.base.orange, italic = true },
    ["@lsp.type.typeParameter.python"] = { link = "Type" },
    ["@lsp.typemod.class.defaultLibrary.python"] = { link = "Type" },
  }
end

return M
